apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "json-store-api.fullname" . }}
  labels: {{- include "json-store-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
